apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: integrated-ex
    labels:
      app: integrated-ex 
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          app: integrated-ex
      spec:
        containers:
          - name: integrated-ex
            image: docker-registry.default.svc:5000/integrated-ex-user06/cloud-native-track-integrated-exercise
            ports: 
            - containerPort: 8080
              protocol: TCP 
- apiVersion: v1
  kind: Service
  metadata:
    name: integrated-ex
  spec:
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      type: NodePort
    selector:
      app: integrated-ex
- apiVersion: v1
  kind: Route
  metadata: 
    name: integrated-ex
  spec:
    to:
      kind: Service
      name: integrated-ex
              
