apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: integrated-ex
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: integrated-ex
    labels:
      app: integrated-ex
  spec:
    runPolicy: Serial
    output:
      to:
        kind: ImageStreamTag
        name: integrated-ex:0.0.1
    source:
      git:
        ref: develop
        uri: https://github.com/JoeriJackers/cloud-native-track-integrated-exercise.git
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: integrated-ex:0.0.1
    triggers:
    - type: ImageChange
    - type: ConfigChange
    - github:
        secret: Password201903
      type: GitHub
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: integrated-ex
    labels:
      app: integrated-ex 
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          app: integrated-ex
      spec:
        containers:
          - name: integrated-ex
            image: docker-registry.default.svc:5000/integrated-ex-user06/integrated-ex:0.0.1
            ports: 
            - containerPort: 8080
              protocol: TCP 
            envFrom:
            - configMapRef:
                name: integrated-ex-env
            resources:
              requests:
                cpu: 500m
                memory: 256Mi
              limits:
                cpu: 1000m
                memory: 512Mi
            readinessProbe:
              httpGet:
                path: /actuator/health
                port: 8080
              initialDelaySeconds: 5
              timeoutSeconds: 5
            livenessProbe:
              httpGet:
                path: /actuator/health
                port: 8080
              initialDelaySeconds: 1
              timeoutSeconds: 1
              failureTreshold: 2
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: integrated-ex-env
  data: 
    ENV: PROD
- apiVersion: v1
  kind: Service
  metadata:
    name: integrated-ex
  spec:
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      type: NodePort
    selector:
      app: integrated-ex
- apiVersion: v1
  kind: Route
  metadata: 
    name: integrated-ex
  spec:
    to:
      kind: Service
      name: integrated-ex
              
